packages:
  - "apps/*"
  - "packages/*"
  - "services/*"

# Catalog for sharing dependencies
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^14.1.0
  
  # TypeScript
  typescript: ^5.3.3
  "@types/react": ^18.2.55
  "@types/react-dom": ^18.2.19
  "@types/node": ^20.11.17
  
  # Styling
  tailwindcss: ^3.4.1
  autoprefixer: ^10.4.17
  postcss: ^8.4.35
  
  # tRPC ecosystem
  "@trpc/client": ^10.45.1
  "@trpc/server": ^10.45.1
  "@trpc/react-query": ^10.45.1
  "@trpc/next": ^10.45.1
  
  # React Query
  "@tanstack/react-query": ^5.20.1
  "@tanstack/react-query-devtools": ^5.20.1
  
  # Authentication
  "next-auth": ^4.24.6
  
  # Form handling
  "react-hook-form": ^7.49.3
  "@hookform/resolvers": ^3.3.4
  
  # Validation
  zod: ^3.22.4
  
  # UI components
  "class-variance-authority": ^0.7.0
  clsx: ^2.1.0
  "tailwind-merge": ^2.2.1
  "lucide-react": ^0.323.0
  
  # Date handling
  "date-fns": ^3.3.1
  
  # Utils
  nanoid: ^5.0.4
  
  # Development tools
  eslint: ^8.56.0
  "@typescript-eslint/eslint-plugin": ^6.21.0
  "@typescript-eslint/parser": ^6.21.0
  "eslint-config-next": ^14.1.0