name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: backend/go.sum

      - name: Update npm dependencies
        run: |
          npm update
          npx npm-check-updates -u
          npm install

      - name: Update Go dependencies
        run: |
          cd backend
          go get -u ./...
          go mod tidy

      - name: Run security audit
        run: |
          npm audit --audit-level=moderate || true
          cd backend && go list -json -deps ./... | nancy sleuth || true

      - name: Run tests
        run: |
          npm test -- --watchAll=false
          cd backend && go test ./...

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated Dependency Updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates for both frontend and backend.
            
            ### Changes
            - Updated npm packages to latest versions
            - Updated Go modules to latest versions
            - Ran security audits
            - All tests passing
            
            Please review the changes and merge if everything looks good.
            
            ---
            🤖 This PR was created automatically by the dependency update workflow.
          branch: feature/dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
          reviewers: |
            # Add your team members here
          assignees: |
            # Add assignees here

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Fix npm vulnerabilities
        run: |
          npm audit fix --force
          
      - name: Run security scan
        run: |
          npm audit --audit-level=high
          
      - name: Create Security PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: fix vulnerabilities'
          title: 'Security: Fix Vulnerabilities'
          body: |
            ## Security Vulnerability Fixes
            
            This PR contains fixes for security vulnerabilities found in dependencies.
            
            ### Changes
            - Applied automatic security fixes
            - Updated vulnerable packages
            - Verified no high-severity vulnerabilities remain
            
            **⚠️ Priority: High - Please review and merge immediately**
            
            ---
            🔒 This PR was created automatically by the security update workflow.
          branch: security/vulnerability-fixes
          delete-branch: true
          labels: |
            security
            critical
            automated
          reviewers: |
            # Add security team members here
          assignees: |
            # Add security assignees here